type = "card"
title = "科研项目与授权专利"
description = "我承担的科研项目与已授权的发明专利。"

[[items]]
title = "异构道路环境下网联车安全队列控制研究"
subtitle = "中央高校基本科研业务费"
date = "2026-01 至 2028-12"
content = "项目编号：B260201905"
tags = ["河海大学", "主持", "在研"]

[[items]]
title = "离散多自主体编队跟踪关键技术研究"
subtitle = "江苏省研究生实践创新计划"
date = "2023-05 至 2024-08"
content = "项目编号：SJCX23_0044"
tags = ["江苏省教育厅", "主持", "已结题"]


[[items]]
title = "💡 授权专利"
content = """
1. 陈杨杨; **刘天润**; 一种面向非线性时空系统的自适应凝结神经跟踪控制方法, 2025-11-25, 中国, ZL202411861341.8
"""