[[news]]
date = "2026-7"
content = "成果入选“2025年度江苏省行业领域（电子信息领域）十大科技进展”"

[[news]]
date = "2026-6"
content = "博士生汪金涛的论文被《The Visual Computer》接收（协助指导）"

[[news]]
date = "2026-2"
content = "入职河海大学人工智能与自动化学院"
