type = "card"
title = "学术兼职"
%description = "专业服务与社区参与。"

[[items]]
title = "分会共同主席"
subtitle = "10th International Symposium on Computer Science and Intelligent Control (ISCSIC 2026)"
date = "2026"

[[items]]
title = "宣传主席"
subtitle = "4th IEEE International Conference on Pattern Recognition, Machine Vision and Artificial Intelligence (IEEE PRMVAI 2026)"
date = "2026"

[[items]]
title = "十余本权威期刊审稿人"
subtitle = "IEEE/CAA Journal of Automatica Sinica、IEEE Transactions on Systems, Man, and Cybernetics: Systems、IEEE Transactions on Industrial Informatics、IEEE Transactions on Neural Networks and Learning Systems、IEEE Transactions on Intelligent Vehicles、Neural Networks、Nonlinear Dynamics"

[[items]]
title = "顶级会议审稿人"
subtitle = "IEEE Conference on Decision and Control (CDC)、American Control Conference (ACC)、European Control Conference (ECC)"